kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      web: production
  replicas: 1
  template:
    metadata:
      labels:
        web: production
    spec:
      containers:
      - name: mywebsite
        image: "docops27/pipeline-k8s-jenkins:latest"
        ports:
          - containerPort: 80
